name: Deploy TempoHome to Raspberry Pi

on:
  push:
    branches:
      - main  # ⚙️ Déclenchement uniquement quand tu merges ou pushes sur la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1️⃣ : Récupère le code depuis GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2️⃣ : Vérifie que le Raspberry Pi est joignable (healthcheck)
    - name: Check if Raspberry Pi is online
      run: |
        echo "🩺 Vérification du Raspberry Pi..."
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://192.168.1.27:8080/health || echo "000")
        if [ "$RESPONSE" != "200" ]; then
          echo "❌ Raspberry Pi offline or unresponsive"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"🚨 **TempoHome** : Raspberry Pi ne répond pas au healthcheck !\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
          exit 1
        fi
        echo "✅ Raspberry Pi est en ligne"

    # Étape 3️⃣ : Déploiement via SSH (pull + restart service)
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          cd /home/aurel/TempoHome
          echo "📦 Pull du dernier code depuis GitHub..."
          git pull
          echo "♻️ Redémarrage du service TempoHome..."
          sudo systemctl restart temphome.service
          echo "✅ Déploiement terminé avec succès."
