# TODO Uncomment Healthcheck and if when the server is up

name: Deploy on Raspberry Pi (Dev)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted  # exécuté directement sur ton Raspberry Pi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Test API Healthcheck (avant déploiement)
#        id: apicheck
#        run: |
#          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health || echo 000)
#          echo "API status code: $STATUS"
#          if [[ "$STATUS" =~ ^(200|201|204)$ ]]; then
#            echo "API healthy"
#          else
#            echo "api_unhealthy=true" >> $GITHUB_ENV
#          fi
#
#      - name: Notify Discord if API failed (avant déploiement)
#        if: env.api_unhealthy == 'true'
#        run: |
#          curl -H "Content-Type: application/json" \
#               -d "{\"content\": \"⚠️ TempoHome Dev : l'API locale ne répond pas, le déploiement est annulé.\"}" \
#               ${{ secrets.DISCORD_WEBHOOK }}
#          exit 1

      - name: Set up Python environment
        #if: env.api_unhealthy != 'true'
        run: |
          echo "🔧 Setting up virtual environment for DEV"
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "⚠️ Aucun requirements.txt trouvé"
          fi

      - name: Run deploy script (DEV)
        #if: env.api_unhealthy != 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh dev

      - name: Notify Discord success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"🧪 Déploiement DEV réussi sur le Raspberry Pi (self-hosted runner).\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"🚨 Échec du déploiement DEV sur le Raspberry Pi.\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
